name: "CodeQL Custom Queries Unit Tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-queries:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # On installe la CLI CodeQL sans initialiser de base de données
    - name: Setup CodeQL CLI
      uses: github/codeql-action/setup-codeql@v4

    - name: Run CodeQL Tests
      run: |
        codeql test run ./codeql-custom-queries-javascript --format=text